// Fulfillment Design System — Brand A (Warehouse Ops)
// Auto-generated by Style Dictionary. DO NOT EDIT.
// Run: node packages/tokens/style-dictionary.config.mjs brand-a

import 'package:flutter/material.dart';

class FdsBrandATokens {
  FdsBrandATokens._();

  // ── Brand colors ─────────────────────────────────────────────────────────
  static const Color colorBrandPrimary        = Color(0xFF0A6EFF);
  static const Color colorBrandPrimaryHover   = Color(0xFF0056D4);
  static const Color colorBrandPrimaryPressed = Color(0xFF0042A4);
  static const Color colorBrandPrimarySubtle  = Color(0xFFE7F0FF);
  static const Color colorBrandOnPrimary      = Color(0xFFFFFFFF);

  static const Color colorBrandSecondary        = Color(0xFF1A2540);
  static const Color colorBrandSecondaryHover   = Color(0xFF101930);
  static const Color colorBrandSecondarySubtle  = Color(0xFFE8ECF4);
  static const Color colorBrandOnSecondary      = Color(0xFFFFFFFF);

  static const Color colorBrandAccent       = Color(0xFFF59E0B);
  static const Color colorBrandAccentSubtle = Color(0xFFFFF8E1);
  static const Color colorBrandOnAccent     = Color(0xFF1A2540);

  // ── Surface ──────────────────────────────────────────────────────────────
  static const Color colorSurfaceDefault  = Color(0xFFFFFFFF);
  static const Color colorSurfaceSunken   = Color(0xFFF4F6FB);
  static const Color colorSurfaceEmphasis = Color(0xFFE8ECF4);

  // ── Text ─────────────────────────────────────────────────────────────────
  static const Color colorTextPrimary   = Color(0xFF1A2540);
  static const Color colorTextSecondary = Color(0xFF4A5568);
  static const Color colorTextTertiary  = Color(0xFF718096);
  static const Color colorTextDisabled  = Color(0xFFA0AEC0);
  static const Color colorTextLink      = Color(0xFF0A6EFF);

  // ── Border ───────────────────────────────────────────────────────────────
  static const Color colorBorderDefault = Color(0xFFDEE2E6);
  static const Color colorBorderStrong  = Color(0xFFCED4DA);
  static const Color colorBorderFocus   = Color(0xFF0A6EFF);

  // ── Feedback ─────────────────────────────────────────────────────────────
  static const Color colorFeedbackSuccess       = Color(0xFF1AAB55);
  static const Color colorFeedbackSuccessSubtle = Color(0xFFE8F9EF);
  static const Color colorFeedbackWarning       = Color(0xFFF59E0B);
  static const Color colorFeedbackWarningSubtle = Color(0xFFFFF8E1);
  static const Color colorFeedbackError         = Color(0xFFE53535);
  static const Color colorFeedbackErrorSubtle   = Color(0xFFFFF0F0);

  // ── Component tokens ─────────────────────────────────────────────────────
  static const double buttonBorderRadius = 6.0;
  static const double cardBorderRadius   = 10.0;
  static const double inputHeight        = 40.0;

  // ── Spacing ──────────────────────────────────────────────────────────────
  static const double spacing1  = 4.0;
  static const double spacing2  = 8.0;
  static const double spacing3  = 12.0;
  static const double spacing4  = 16.0;
  static const double spacing6  = 24.0;
  static const double spacing8  = 32.0;
  static const double spacing10 = 40.0;
  static const double spacing12 = 48.0;

  // ── Typography ───────────────────────────────────────────────────────────
  static const double fontSizeXs  = 11.0;
  static const double fontSizeSm  = 13.0;
  static const double fontSizeMd  = 15.0;
  static const double fontSizeLg  = 17.0;
  static const double fontSizeXl  = 20.0;
  static const double fontSize2xl = 24.0;
  static const double fontSize3xl = 30.0;

  static const FontWeight fontWeightRegular  = FontWeight.w400;
  static const FontWeight fontWeightMedium   = FontWeight.w500;
  static const FontWeight fontWeightSemibold = FontWeight.w600;
  static const FontWeight fontWeightBold     = FontWeight.w700;
}
