/**
 * Style Dictionary configuration for Fulfillment Design System.
 *
 * Reads W3C DTCG tokens (core + semantic + brand override) and produces:
 *   - CSS custom properties (web / Storybook)
 *   - ES module JS constants (React components)
 *   - Dart constants (Flutter)
 *
 * Usage:
 *   node style-dictionary.config.mjs          # build all brands
 *   node style-dictionary.config.mjs brand-a  # build one brand
 */

import StyleDictionary from 'style-dictionary';
import { fileHeader } from 'style-dictionary/utils';

const BRANDS = ['brand-a', 'brand-b'];

// ─── Custom Dart formatter ────────────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'dart/class',
  format: async ({ dictionary, options, file }) => {
    const header = await fileHeader({ file });
    const className = options.className || 'FdsTokens';

    const lines = dictionary.allTokens.map((token) => {
      const name = token.name
        .replace(/-([a-z])/g, (_, c) => c.toUpperCase())
        .replace(/^./, (c) => c.toLowerCase());

      const raw = token.$value ?? token.value;
      let dartValue;

      if (typeof raw === 'string' && raw.startsWith('#')) {
        const hex = raw.slice(1);
        const alpha = hex.length === 8 ? hex.slice(0, 2) : 'ff';
        const rgb   = hex.length === 8 ? hex.slice(2) : hex;
        dartValue = `const Color(0x${alpha}${rgb.toUpperCase()})`;
      } else if (typeof raw === 'string' && raw.endsWith('px')) {
        dartValue = `${parseFloat(raw)}`;
      } else {
        dartValue = `'${raw}'`;
      }

      return `  static ${typeof raw === 'string' && raw.startsWith('#') ? 'Color' : 'dynamic'} ${name} = ${dartValue};`;
    });

    return [
      header,
      "import 'package:flutter/material.dart';",
      '',
      `class ${className} {`,
      `  ${className}._();`,
      ...lines,
      '}',
      '',
    ].join('\n');
  },
});

// ─── Custom JS/TS formatter ───────────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'javascript/es6-const',
  format: async ({ dictionary, file }) => {
    const header = await fileHeader({ file });
    const lines = dictionary.allTokens.map((token) => {
      const name = token.name
        .replace(/-([a-z])/g, (_, c) => c.toUpperCase())
        .replace(/^./, (c) => c.toLowerCase());
      const value = token.$value ?? token.value;
      return `export const ${name} = ${JSON.stringify(value)};`;
    });
    return [header, ...lines, ''].join('\n');
  },
});

// ─── Build per brand ─────────────────────────────────────────────────────────
async function buildBrand(brand) {
  const sd = new StyleDictionary({
    source: [
      'src/core.json',
      'src/semantic.json',
      `src/brands/${brand}.json`,
    ],
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: 'fds',
        buildPath: `dist/${brand}/`,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables',
            options: {
              selector: `[data-brand="${brand}"]`,
              outputReferences: true,
              fileHeader: () => [
                `Fulfillment Design System — ${brand}`,
                'Auto-generated by Style Dictionary. DO NOT EDIT.',
              ],
            },
          },
        ],
      },
      js: {
        transformGroup: 'js',
        buildPath: `dist/${brand}/`,
        files: [
          {
            destination: 'tokens.js',
            format: 'javascript/es6-const',
            options: {
              fileHeader: () => [
                `Fulfillment Design System — ${brand}`,
                'Auto-generated by Style Dictionary. DO NOT EDIT.',
              ],
            },
          },
        ],
      },
      flutter: {
        transformGroup: 'js',
        buildPath: `dist/flutter/`,
        files: [
          {
            destination: `${brand.replace('-', '_')}_tokens.dart`,
            format: 'dart/class',
            options: {
              className: `Fds${brand.split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('')}Tokens`,
              fileHeader: () => [
                `Fulfillment Design System — ${brand} (Flutter)`,
                'Auto-generated by Style Dictionary. DO NOT EDIT.',
              ],
            },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  console.log(`✅  Built ${brand}`);
}

const targetBrand = process.argv[2];
const brands = targetBrand ? [targetBrand] : BRANDS;

for (const brand of brands) {
  await buildBrand(brand);
}
console.log('\n🎉  Token build complete.');
